const ENV_COINGECKO_API_BASE_URL = 'COINGECKO_API_BASE_URL';
const ENV_PORT = 'PORT';
const ENV_JWT_SECRET = 'JWT_SECRET';

export {
    ENV_COINGECKO_API_BASE_URL,
    ENV_PORT,
    ENV_JWT_SECRET
};