const ENV_COINGECKO_API_BASE_URL = 'COINGECKO_API_BASE_URL';
const ENV_PORT = 'PORT';
const ENV_JWT_SECRET = 'JWT_SECRET';
const ENV_MAILGUN_USERNAME = 'MAILGUN_USERNAME';
const ENV_MAILGUN_API_KEY = 'MAILGUN_API_KEY';
const ENV_REDIS_HOST = 'REDIS_HOST';
const ENV_REDIS_PORT = 'REDIS_PORT';
const ENV_MAILGUN_DOMAIN_NAME = 'MAILGUN_DOMAIN_NAME';
const ENV_MAILGUN_TEMPLATE_EMAIL_VERIFICATION = 'MAILGUN_TEMPLATE_EMAIL_VERIFICATION';
const ENV_MAILGUN_TEMPLATE_PASSWORD_RESET = 'MAILGUN_TEMPLATE_PASSWORD_RESET';
const ENV_MAILGUN_TEMPLATE_PRICE_ALERT = 'MAILGUN_TEMPLATE_PRICE_ALERT';
const ENV_BASE_URL = 'BASE_URL';

const PARAM_COINGECKO_DEFAULT_VS_CURRENCIES = 'brl';
const PARAM_COINGECKO_DEFAULT_PRECISION = 18;

const PATH_ACCOUNT_VERIFICATION = `auth/verify-account`;

const QUEUE_MAIL_SENDING = 'mailSending-queue';
const QUEUE_ALERT_TRIGGERING = 'alertTriggering-queue';
const JOB_MAIL_SENDING = 'mailSending-job';
const JOB_ALERT_TRIGGERING = 'alertTriggering-job';

const EMAIL_FROM = 'noreply@localhost';

export {
    ENV_COINGECKO_API_BASE_URL,
    ENV_PORT,
    ENV_JWT_SECRET,
    ENV_MAILGUN_USERNAME,
    ENV_MAILGUN_API_KEY,
    ENV_MAILGUN_DOMAIN_NAME,
    ENV_REDIS_HOST,
    ENV_REDIS_PORT,
    ENV_MAILGUN_TEMPLATE_EMAIL_VERIFICATION,
    ENV_MAILGUN_TEMPLATE_PASSWORD_RESET,
    ENV_MAILGUN_TEMPLATE_PRICE_ALERT,
    ENV_BASE_URL,
    PARAM_COINGECKO_DEFAULT_VS_CURRENCIES,
    PARAM_COINGECKO_DEFAULT_PRECISION,
    QUEUE_MAIL_SENDING,
    QUEUE_ALERT_TRIGGERING,
    JOB_MAIL_SENDING,
    JOB_ALERT_TRIGGERING,
    PATH_ACCOUNT_VERIFICATION,
    EMAIL_FROM
};