const ENV_COINGECKO_API_BASE_URL = 'COINGECKO_API_BASE_URL';
const ENV_PORT = 'PORT';
const ENV_JWT_SECRET = 'JWT_SECRET';
const ENV_MAILGUN_USERNAME = 'MAILGUN_USERNAME';
const ENV_MAILGUN_API_KEY = 'MAILGUN_API_KEY';
const ENV_REDIS_HOST = 'REDIS_HOST';
const ENV_REDIS_PORT = 'REDIS_PORT';
const ENV_MAILGUN_DOMAIN_NAME = 'MAILGUN_DOMAIN_NAME';
const ENV_MAILGUN_TEMPLATE_EMAIL_VERIFICATION = 'MAILGUN_TEMPLATE_EMAIL_VERIFICATION'
const ENV_BASE_URL = 'BASE_URL';

const PATH_ACCOUNT_VERIFICATION = `auth/verify-account`;

const QUEUE_MAIL_SENDING = 'mailSending-queue';
const JOB_MAIL_SENDING = 'mailSending-job';

const EMAIL_FROM = 'noreply@localhost';

export {
    ENV_COINGECKO_API_BASE_URL,
    ENV_PORT,
    ENV_JWT_SECRET,
    ENV_MAILGUN_USERNAME,
    ENV_MAILGUN_API_KEY,
    ENV_MAILGUN_DOMAIN_NAME,
    ENV_REDIS_HOST,
    ENV_REDIS_PORT,
    ENV_MAILGUN_TEMPLATE_EMAIL_VERIFICATION,
    ENV_BASE_URL,
    QUEUE_MAIL_SENDING,
    JOB_MAIL_SENDING,
    PATH_ACCOUNT_VERIFICATION,
    EMAIL_FROM
};